version: '3.8'

services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      MONGO_INITDB_DATABASE: blog

  rest_api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rest_api
    restart: unless-stopped
    ports:
      - "3011:3011"
    depends_on:
      - mongo
    env_file:
      - ./docker-compose.env
    volumes:
      - .:/app
